# Generated by Django 2.2.5 on 2020-04-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_liked_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_child_comments',
            field=models.TextField(default='[]'),
        ),
    ]
