# Generated by Django 2.2.5 on 2020-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_liked_child_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.TextField(default='[]'),
        ),
    ]
