# Generated by Django 2.2.5 on 2020-04-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.TextField(default='[]'),
        ),
    ]
