# Generated by Django 2.2.5 on 2020-04-29 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200429_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
